---
- name: Setup WebServer
  hosts: webserver
  gather_facts: false
  tasks:
    - name: Install httpd package
      dnf:
        name:
          - httpd
          - firewalld
        state: present

    - name: start service httpd
      service:
        name: httpd
        state: started
        enabled: yes
   
    - name: start service firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
 
    - name: Add http service in firewall rule
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes

    - name: Copy web content
      copy:
        content: "Learning RHCE"
      dest: /var/www/html/index.html
