---
- name: play to update issue file
  hosts: all
  tasks:
    - name: replace the content in dev group
      copy:
        content: Development
        dest: /etc/issue
      when: inventory_hostname in groups['dev']
    
    - name: replace the content in test group
      copy:
        content: Test
        dest: /etc/issue
      when: inventory_hostname in groups['test']

    - name: replace the content in prod group
      copy:
        content: Production
        dest: /etc/issue
      when: inventory_hostname in groups['prod']
